### ISSUE TITLE
Microphone not working when making videos

### ISSUE THREAD

**Issue by Elvettorato** [halal-beef/lineage_release_hub#1]
Microphone doesn't seem to work when you record a video, if needed i will take a logcat

**Comment by halal-beef** [comment]
Disable the microphone in the Google app, reboot and try recording again

**Comment by Elvettorato** [comment]
> Disable the microphone in the Google app, reboot and try recording again

Just tried, no change, and i noticed than none of the apps can access the microphone, i tried to change the microphone channel on Open Camera, but still nothing

**Comment by halal-beef** [comment]
works fine for me on aperture after disabling the mic on the Google app, I'll see what I can do

**Comment by Elvettorato** [comment]
> works fine for me on aperture after disabling the mic on the Google app, I'll see what I can do

Alright, problem solved by UNINSTALLING the google app with adb, sorry for bothering you

**Comment by halal-beef** [comment]
addressed in https://github.com/halal-beef/lineage_release_hub/releases/tag/x1s-20240819
